spring.application.name=saloon-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/salon_booking_db
spring.datasource.username=postgres
spring.datasource.password=StrongPass@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
